### ISSUE TITLE
Fix wharf for latest version of docker

### ISSUE THREAD

**Issue by bargulg** [RedHatQE/webdriver-wharf#12]
I'm getting an error with docker version: 1.12.6, build 96d83a5/1.12.6
APIError: 400 Client Error: Bad Request ("{"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}")

Description of problem and solution is here: https://github.com/docker/docker-py/issues/1267

**Comment by mfalesni** [comment]
#13 is an experiment to address this issue.

**Comment by jchristi** [comment]
#13 was merged so can this be closed?

**Comment by RonnyPfannschmidt** [comment]
yes, im waiting for my perms
