### ISSUE TITLE
Allow wharf to work with a remote Docker host

### ISSUE THREAD

**Issue by jchristi** [RedHatQE/webdriver-wharf#6]
Currently, webdriver-wharf expects that the docker daemon is being run on the same host as it is. There are several advantages to allowing wharf to connect to a remote docker host, such as: 
- Decoupling for increased resiliency. Makes upgrades and maintenance easier by allowing them to be operated on individually.
- Re-use existing docker infrastructure. There's nothing special about wharf that makes it require its own docker daemon. You could easily piggyback off someone else's docker host(s) and further reduce maintenance burden.
- Allows for use with cloud container services, like [Amazon EC2 Container Service](https://aws.amazon.com/ecs/) and maybe OpenShift.

This really shouldn't be too difficult to change (I think). Just make some modifications to the docker calls and some config options for docker host location. This one isn't as immediately important to me as the port issue, so that should take priority.

**Comment by jchristi** [comment]
Depending on the network and firewall configuration of the docker hosts, you could also have an option to choose to use wharf as a reverse proxy or to return the direct URL of the remote container so as not to add another network hop.

**Comment by RonnyPfannschmidt** [comment]
the difficulty in this change is the connection endpoint mapping - with the current api consumer cant even remotely be made aware - and just proxying is a very costly alternative that also inhibits various sensible protocols (like vnc)

its def doable, but great care has to be put into the host mapping/proxying

**Comment by RonnyPfannschmidt** [comment]
i did a little review - we have `docker.from_env` so setting it up with a envvar as the docker client expects should suffice
